### ISSUE TITLE
fosdk not building when used as submodule

### ISSUE THREAD

**Issue by davidmalanaphy** [blu-corner/fosdk#27]
when adding the repo as a submodule within the simulator, it is not building correctly with the following error: 

[ 98%] Building CXX object src/bindings/python/CMakeFiles/_pyFosdk.dir/CMakeFiles/_pyFosdk.dir/fosdkPYTHON_wrap.cxx.o
/home/dmalanaphy/sim/build/src/FOSDK_PROJECT-build/src/bindings/python/CMakeFiles/_pyFosdk.dir/fosdkPYTHON_wrap.cxx:3575:10: fatal error: ../../ext/codec/src/bindings/codecBuffer.h: No such file or directory
 #include "../../ext/codec/src/bindings/codecBuffer.h"

**Comment by philberty** [comment]
We need to copy this over from codec will resolve this issue and change the path in the interface file

**Comment by colinpattison** [comment]
Closing as done
